### ISSUE TITLE
Convert project to Cmake

### ISSUE THREAD

**Issue by RosaryMala** [gavanw/voxelquestiso#2]
If cross-platform is going to become an option, it would be a good idea to convert this to a cmake project, and let it handle generating the visual studio projects, as well as dependencies.

**Comment by gavanw** [comment]
Yep, I was just discussing that on Hacker News :) https://news.ycombinator.com/item?id=12221559

**Comment by MoreMoschops** [comment]
As a single extra data point, I had VS2015 try to build it. After converting everything from VS2012 to VS2015, and then after I turned off the automatic "helping" involving git repositories (honestly, sometimes Microsoft products make me want to scream - they "help" like a five year old child helps with the shopping, constantly in the way and adding things without telling you) and also turned off the automatically activated whole project optimisation in the linker so that the linker stopped crashing, it simply doesn't build. Looks like a selection of failed commands in something called "combine.bat", involving copying files. I have no idea; I only use VS when I'm forced to.

As an aside, I see you're using lzz. You're the second person I've ever come across who uses it (it's on the banned list at my current workplace, which was the only way to get someone to stop using it).

**Comment by TheKnarf** [comment]
I agree that this should be converted to CMake. If @gavanw care to fix issue #5 then I might take a stab at this issue afterwards.
